### ISSUE TITLE
Manager Immunity

### ISSUE THREAD

**Issue by FSG-Cat** [the-draupnir-project/Draupnir#265] opened 2024-02-25 16:20 UTC
Make people in the control room be immune from the bot. 

Currently this is bypassed by communities like for example Privacy Guides last i heard by having all moderators be at higher PL than the bot. To make it so no rouge admin can for example cause havoc by writing a CME ban for a PG mod without giving them a chance to make their on decision on the validity of the policy. 

This would also make it so you can make your bot shut up when in a situation where you have users that the bot wants to ban but they are too high PL and also are managers anyways so this feature would make the bot happy.

**Comment by Mikaela** [comment] 2024-02-25 18:18
Duplicate of #161.

**Closed by Mikaela** 2024-02-25 18:18 UTC
Labels: enhancement, L2 Few, P1 Nuisance, T3 Workflow Issue
