### ISSUE TITLE
Store configuration to disk or elsewhere reliable / Matrix state resets keep altering configuration and banning benevolent users for "spam"

### ISSUE THREAD

**Issue by Mikaela** [the-draupnir-project/Draupnir#196] opened 2024-01-04 17:58 UTC
I have three times disabled `basicfloodingprotection` as it keeps triggering on redactions or other expected Matrix behaviour (#187), but the change gets reverted as Matrix cannot be trusted for things such as software configuration.

Thus I think the configuration should be stored on disk or something like software usually does.

Ref: https://github.com/matrix-org/synapse/issues/8629

**Comment by Gnuxie** [comment] 2024-01-21 16:56
This doesn't seem to be caused by state resets, since the list of enabled protections is loaded from [account data](https://github.com/the-draupnir-project/Draupnir/blob/main/src/protections/ProtectionManager.ts#L91). However this is still a Major usability issue.

**Comment by Mikaela** [comment] 2024-01-28 05:19
And this happens again. Were there any ideas on what causes it, if not state resets?

**Comment by Gnuxie** [comment] 2024-01-28 21:26
To be confirmed, but we suspect that under certain conditions where synapse starts and then later loses a connection to the database, it will return empty account data with a http OK response. Meaning that we have no way to detect this failure mode.

**Comment by Gnuxie** [comment] 2024-01-28 23:44
OK turns out there was a Synapse+Redis problem specific to draupnir.midnightthoughts.space CC @MTRNord will close on confirmation.

**Comment by MTRNord** [comment] 2024-01-30 09:01
I am monitoring this but it seems to have been resolved after the redis was fixed. Closing :)

**Closed by MTRNord** 2024-01-30 09:01 UTC
Labels: bug, enhancement, L3 Some Users, P3 Outrageous / Cannot continue to or start to use, T5  Major usability
