### ISSUE TITLE
Draupnir repeatedly throws an error when report polling is enabled (beta6)

### ISSUE THREAD

**Issue by TheArcaneBrony** [the-draupnir-project/Draupnir#583] opened 2024-09-26 23:34 UTC
![image](https://github.com/user-attachments/assets/07763ecc-f24b-4a42-b33c-5602273c7533)

**Comment by Gnuxie** [comment] 2024-10-04 22:35
Duplicate of https://github.com/the-draupnir-project/Draupnir/issues/258

**Closed by Gnuxie** 2024-10-04 22:35 UTC
Labels: L2 Few
